### ISSUE TITLE
build failed at UE 4.19.2-release

### ISSUE THREAD

**Issue by flavorfan** [ue4plugins/MobuLiveLink#10]
build failed at UE 4.19.2-release.

error in MobuLiveLinkDevice.cpp   , FFrameRate undeclared identifier

------ Build started: Project: DotNETUtilities, Configuration: Development Any CPU ------
  DotNETUtilities -> D:\flavor\UnrealEngine\Engine\Binaries\DotNET\DotNETUtilities.dll
------ Build started: Project: UnrealBuildTool, Configuration: Development Any CPU ------
  UnrealBuildTool -> D:\flavor\UnrealEngine\Engine\Binaries\DotNET\UnrealBuildTool.exe
------ Build started: Project: MobuLiveLinkPlugin, Configuration: Development_Program x64 ------
  Using 'git status' to determine working set for adaptive non-unity build.
  Creating makefile for MobuLiveLinkPlugin (no existing makefile)
  Performing full C++ include scan (no include cache file)
  Building UnrealHeaderTool...
  Using 'git status' to determine working set for adaptive non-unity build.
  Creating makefile for UnrealHeaderTool (no existing makefile)
  Performing full C++ include scan (no include cache file)
  Performing 37 actions (15 in parallel)
  [4/37] Resource PCLaunch.rc
  [7/37] Resource PCLaunch.rc
  [2/37] Resource ModuleVersionResource.rc.inl
  PCH.Core.cpp
  SharedPCH.Core.cpp
  PCH.CoreUObject.cpp
  Module.UnrealHeaderTool.cpp
  Module.Json.cpp
  Module.Projects.cpp
  Module.ApplicationCore.cpp
  Module.Core.8_of_9.cpp
  Module.Core.3_of_9.cpp
  Module.Core.5_of_9.cpp
  Module.Core.7_of_9.cpp
  Module.Core.4_of_9.cpp
  Module.Core.9_of_9.cpp
  Module.Core.6_of_9.cpp
  Module.Core.1_of_9.cpp
  Module.Core.2_of_9.cpp
  [20/37] Link UnrealHeaderTool-Projects.lib
  [21/37] Link UnrealHeaderTool-ApplicationCore.lib
     Creating library D:\flavor\UnrealEngine\Engine\Intermediate\Build\Win64\UnrealHeaderTool\Development\UnrealHeaderTool-Projects.lib and object D:\flavor\UnrealEngine\Engine\Intermediate\Build\Win64\UnrealHeaderTool\Development\UnrealHeaderTool-Projects.exp
     Creating library D:\flavor\UnrealEngine\Engine\Intermediate\Build\Win64\UnrealHeaderTool\Development\UnrealHeaderTool-ApplicationCore.lib and object D:\flavor\UnrealEngine\Engine\Intermediate\Build\Win64\UnrealHeaderTool\Development\UnrealHeaderTool-ApplicationCore.exp
  Module.CoreUObject.3_of_6.cpp
  Module.CoreUObject.6_of_6.cpp
  Module.CoreUObject.2_of_6.cpp
  Module.CoreUObject.4_of_6.cpp
  Module.CoreUObject.5_of_6.cpp
  Module.CoreUObject.1_of_6.cpp
  [28/37] Link UnrealHeaderTool-Json.lib
     Creating library D:\flavor\UnrealEngine\Engine\Intermediate\Build\Win64\UnrealHeaderTool\Development\UnrealHeaderTool-Json.lib and object D:\flavor\UnrealEngine\Engine\Intermediate\Build\Win64\UnrealHeaderTool\Development\UnrealHeaderTool-Json.exp
  [29/37] Link UnrealHeaderTool-Core.lib
  [30/37] Link UnrealHeaderTool-Core.dll
     Creating library D:\flavor\UnrealEngine\Engine\Intermediate\Build\Win64\UnrealHeaderTool\Development\UnrealHeaderTool-Core.lib and object D:\flavor\UnrealEngine\Engine\Intermediate\Build\Win64\UnrealHeaderTool\Development\UnrealHeaderTool-Core.exp
  [31/37] Link UnrealHeaderTool-Projects.dll
  [32/37] Link UnrealHeaderTool-ApplicationCore.dll
  [33/37] Link UnrealHeaderTool-Json.dll
     Creating library D:\flavor\UnrealEngine\Engine\Intermediate\Build\Win64\UnrealHeaderTool\Development\UnrealHeaderTool-Core.suppressed.lib and object D:\flavor\UnrealEngine\Engine\Intermediate\Build\Win64\UnrealHeaderTool\Development\UnrealHeaderTool-Core.suppressed.exp
     Creating library D:\flavor\UnrealEngine\Engine\Intermediate\Build\Win64\UnrealHeaderTool\Development\UnrealHeaderTool-Json.suppressed.lib and object D:\flavor\UnrealEngine\Engine\Intermediate\Build\Win64\UnrealHeaderTool\Development\UnrealHeaderTool-Json.suppressed.exp
     Creating library D:\flavor\UnrealEngine\Engine\Intermediate\Build\Win64\UnrealHeaderTool\Development\UnrealHeaderTool-Projects.suppressed.lib and object D:\flavor\UnrealEngine\Engine\Intermediate\Build\Win64\UnrealHeaderTool\Development\UnrealHeaderTool-Projects.suppressed.exp
     Creating library D:\flavor\UnrealEngine\Engine\Intermediate\Build\Win64\UnrealHeaderTool\Development\UnrealHeaderTool-ApplicationCore.suppressed.lib and object D:\flavor\UnrealEngine\Engine\Intermediate\Build\Win64\UnrealHeaderTool\Development\UnrealHeaderTool-ApplicationCore.suppressed.exp
  [34/37] Link UnrealHeaderTool.lib
     Creating library D:\flavor\UnrealEngine\Engine\Intermediate\Build\Win64\UnrealHeaderTool\Development\UnrealHeaderTool.lib and object D:\flavor\UnrealEngine\Engine\Intermediate\Build\Win64\UnrealHeaderTool\Development\UnrealHeaderTool.exp
  [35/37] Link UnrealHeaderTool-CoreUObject.lib
  [36/37] Link UnrealHeaderTool-CoreUObject.dll
     Creating library D:\flavor\UnrealEngine\Engine\Intermediate\Build\Win64\UnrealHeaderTool\Development\UnrealHeaderTool-CoreUObject.lib and object D:\flavor\UnrealEngine\Engine\Intermediate\Build\Win64\UnrealHeaderTool\Development\UnrealHeaderTool-CoreUObject.exp
     Creating library D:\flavor\UnrealEngine\Engine\Intermediate\Build\Win64\UnrealHeaderTool\Development\UnrealHeaderTool-CoreUObject.suppressed.lib and object D:\flavor\UnrealEngine\Engine\Intermediate\Build\Win64\UnrealHeaderTool\Development\UnrealHeaderTool-CoreUObject.suppressed.exp
  [37/37] Link UnrealHeaderTool.exe
  Total build time: 39.90 seconds (Local executor: 38.55 seconds)
  Parsing headers for MobuLiveLinkPlugin
    Running UnrealHeaderTool MobuLiveLinkPlugin "D:\flavor\UnrealEngine\Engine\Intermediate\Build\Win64\MobuLiveLinkPlugin\Development\MobuLiveLinkPlugin.uhtmanifest" -LogCmds="loginit warning, logexit warning, logdatabase error" -Unattended -WarningsAsErrors -NoEnginePlugins
  Reflection code generated for MobuLiveLinkPlugin in 1.2590022 seconds
  Performing 37 actions (15 in parallel)
  PCH.Core.cpp
  Module.LiveLinkInterface.gen.cpp
  Module.LiveLinkMessageBusFramework.cpp
  Module.LiveLinkMessageBusFramework.gen.cpp
  PCH.CoreUObject.cpp
  Module.LiveLinkInterface.cpp
  Module.Messaging.cpp
  Module.Serialization.cpp
  Module.Networking.cpp
  Module.Sockets.cpp
  Module.UdpMessaging.cpp
  Module.MessagingCommon.cpp
  Module.MobuLiveLinkPlugin.cpp
  Module.SandboxFile.cpp
  Module.UdpMessaging.gen.cpp
  Module.ApplicationCore.cpp
  Module.Projects.cpp
  Module.Core.9_of_9.cpp
  Module.Core.8_of_9.cpp
  Module.Core.6_of_9.cpp
  Module.Core.5_of_9.cpp
  Module.Core.4_of_9.cpp
  Module.Core.3_of_9.cpp
  Module.Core.2_of_9.cpp
D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Public\MobuLiveLinkDevice.h(68): error C2065: 'FFrameRate': undeclared identifier
D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Public\MobuLiveLinkDevice.h(68): error C2923: 'TPair': 'FFrameRate' is not a valid template type argument for parameter 'ValueType'
D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Public\MobuLiveLinkDevice.h(78): error C3646: 'CurrentSampleRate': unknown override specifier
D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Public\MobuLiveLinkDevice.h(78): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
  Module.Core.1_of_9.cpp
D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Public\MobuLiveLinkDevice.h(68): error C2062: type 'unknown-type' unexpected
D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Public\MobuLiveLinkDevice.h(71): error C2065: 'FFrameRate': undeclared identifier
D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Public\MobuLiveLinkDevice.h(71): error C2923: 'TPair': 'FFrameRate' is not a valid template type argument for parameter 'ValueType'
D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Public\MobuLiveLinkDevice.h(72): error C2065: 'FFrameRate': undeclared identifier
D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Public\MobuLiveLinkDevice.h(72): error C2923: 'TPair': 'FFrameRate' is not a valid template type argument for parameter 'ValueType'
D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Public\MobuLiveLinkDevice.h(73): error C2065: 'FFrameRate': undeclared identifier
D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Public\MobuLiveLinkDevice.h(73): error C2923: 'TPair': 'FFrameRate' is not a valid template type argument for parameter 'ValueType'
D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Public\MobuLiveLinkDevice.h(74): error C2065: 'FFrameRate': undeclared identifier
D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Public\MobuLiveLinkDevice.h(74): error C2923: 'TPair': 'FFrameRate' is not a valid template type argument for parameter 'ValueType'
D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Public\MobuLiveLinkDevice.h(75): error C2065: 'FFrameRate': undeclared identifier
D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Public\MobuLiveLinkDevice.h(75): error C2923: 'TPair': 'FFrameRate' is not a valid template type argument for parameter 'ValueType'
D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Public\MobuLiveLinkDevice.h(76): error C2143: syntax error: missing ';' before '}'
D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Public\MobuLiveLinkDevice.h(68): error C2512: 'TArray': no appropriate default constructor available
  d:\flavor\unrealengine\engine\source\runtime\core\public\Containers/Array.h(278): note: see declaration of 'TArray'
D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Public\MobuLiveLinkDevice.h(83): error C2059: syntax error: 'member initializer'
D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Public\MobuLiveLinkDevice.h(103): error C2059: syntax error: '<L_GRAMMAR_end_class>'
D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Public\MobuLiveLinkUtilities.h(16): error C3646: 'TimeModeToFrameRate': unknown override specifier
D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Public\MobuLiveLinkUtilities.h(16): error C2275: 'ORSDK2017::FBTimeMode': illegal use of this type as an expression
  C:\Program Files\Autodesk\MotionBuilder 2017\OpenRealitySDK\include\fbsdk/fbtime.h(63): note: see declaration of 'ORSDK2017::FBTimeMode'
D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Public\MobuLiveLinkUtilities.h(16): error C2146: syntax error: missing ')' before identifier 'TimeMode'
D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Public\MobuLiveLinkUtilities.h(16): error C2238: unexpected token(s) preceding ';'
D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Public\MobuLiveLinkUtilities.h(17): error C2061: syntax error: identifier 'FQualifiedFrameTime'
D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Private\MobuLiveLinkDevice.cpp(55): error C2065: 'CurrentSampleRate': undeclared identifier
D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Private\MobuLiveLinkDevice.cpp(55): error C2661: 'TArray<InElementType,InAllocator>::Last': no overloaded function takes 0 arguments
D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Private\MobuLiveLinkDevice.cpp(55): error C2228: left of '.Value' must have class/struct/union
D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Private\MobuLiveLinkDevice.cpp(94): error C2065: 'CurrentSampleRate': undeclared identifier
D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Private\MobuLiveLinkDevice.cpp(94): error C3861: 'FFrameRate': identifier not found
D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Private\MobuLiveLinkDevice.cpp(112): error C2065: 'CurrentSampleRate': undeclared identifier
D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Private\MobuLiveLinkDevice.cpp(112): error C2228: left of '.Denominator' must have class/struct/union
  D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Private\MobuLiveLinkDevice.cpp(112): note: type is 'unknown-type'
D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Private\MobuLiveLinkDevice.cpp(112): error C2228: left of '.Numerator' must have class/struct/union
  D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Private\MobuLiveLinkDevice.cpp(112): note: type is 'unknown-type'
D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Private\MobuLiveLinkDevice.cpp(268): error C2662: 'int32 TArray<InElementType,InAllocator>::Num(void) const': cannot convert 'this' pointer from 'const TArray' to 'const TArray<InElementType,InAllocator> &'
  D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Private\MobuLiveLinkDevice.cpp(268): note: Reason: cannot convert from 'const TArray' to 'const TArray<InElementType,InAllocator>'
  D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Private\MobuLiveLinkDevice.cpp(268): note: Conversion requires a second user-defined-conversion operator or constructor
D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Private\MobuLiveLinkDevice.cpp(270): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Private\MobuLiveLinkDevice.cpp(270): error C2143: syntax error: missing ';' before '&'
D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Private\MobuLiveLinkDevice.cpp(270): error C2065: 'TestSampleRate': undeclared identifier
D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Private\MobuLiveLinkDevice.cpp(270): error C2678: binary '[': no operator found which takes a left-hand operand of type 'const TArray' (or there is no acceptable conversion)
  d:\flavor\unrealengine\engine\source\runtime\core\public\Containers/Array.h(665): note: could be 'const InElementType &TArray<InElementType,InAllocator>::operator [](int32) const'
  d:\flavor\unrealengine\engine\source\runtime\core\public\Containers/Array.h(652): note: or       'InElementType &TArray<InElementType,InAllocator>::operator [](int32)'
  D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Private\MobuLiveLinkDevice.cpp(270): note: while trying to match the argument list '(const TArray, int)'
D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Private\MobuLiveLinkDevice.cpp(270): error C2228: left of '.Value' must have class/struct/union
D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Private\MobuLiveLinkDevice.cpp(271): error C2065: 'CurrentSampleRate': undeclared identifier
D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Private\MobuLiveLinkDevice.cpp(271): error C2065: 'TestSampleRate': undeclared identifier
D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Private\MobuLiveLinkDevice.cpp(353): error C2662: 'int32 TArray<InElementType,InAllocator>::Num(void) const': cannot convert 'this' pointer from 'const TArray' to 'const TArray<InElementType,InAllocator> &'
  D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Private\MobuLiveLinkDevice.cpp(353): note: Reason: cannot convert from 'const TArray' to 'const TArray<InElementType,InAllocator>'
  D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Private\MobuLiveLinkDevice.cpp(353): note: Conversion requires a second user-defined-conversion operator or constructor
D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Private\MobuLiveLinkDevice.cpp(355): error C2065: 'CurrentSampleRate': undeclared identifier
D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Private\MobuLiveLinkDevice.cpp(355): error C2678: binary '[': no operator found which takes a left-hand operand of type 'const TArray' (or there is no acceptable conversion)
  d:\flavor\unrealengine\engine\source\runtime\core\public\Containers/Array.h(665): note: could be 'const InElementType &TArray<InElementType,InAllocator>::operator [](int32) const'
  d:\flavor\unrealengine\engine\source\runtime\core\public\Containers/Array.h(652): note: or       'InElementType &TArray<InElementType,InAllocator>::operator [](int32)'
  D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Private\MobuLiveLinkDevice.cpp(355): note: while trying to match the argument list '(const TArray, int32)'
D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Private\MobuLiveLinkDevice.cpp(355): error C2228: left of '.Value' must have class/struct/union
D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Private\MobuLiveLinkLayout.cpp(141): error C2662: 'int32 TArray<InElementType,InAllocator>::Num(void) const': cannot convert 'this' pointer from 'const TArray' to 'const TArray<InElementType,InAllocator> &'
  D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Private\MobuLiveLinkLayout.cpp(141): note: Reason: cannot convert from 'const TArray' to 'const TArray<InElementType,InAllocator>'
  D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Private\MobuLiveLinkLayout.cpp(141): note: Conversion requires a second user-defined-conversion operator or constructor
D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Private\MobuLiveLinkLayout.cpp(143): error C2065: 'FFrameRate': undeclared identifier
D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Private\MobuLiveLinkLayout.cpp(143): error C2923: 'TPair': 'FFrameRate' is not a valid template type argument for parameter 'ValueType'
D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Private\MobuLiveLinkLayout.cpp(143): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Private\MobuLiveLinkLayout.cpp(143): error C2144: syntax error: 'unknown-type' should be preceded by ';'
D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Private\MobuLiveLinkLayout.cpp(143): error C2678: binary '[': no operator found which takes a left-hand operand of type 'const TArray' (or there is no acceptable conversion)
  d:\flavor\unrealengine\engine\source\runtime\core\public\Containers/Array.h(665): note: could be 'const InElementType &TArray<InElementType,InAllocator>::operator [](int32) const'
  d:\flavor\unrealengine\engine\source\runtime\core\public\Containers/Array.h(652): note: or       'InElementType &TArray<InElementType,InAllocator>::operator [](int32)'
  D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Private\MobuLiveLinkLayout.cpp(143): note: while trying to match the argument list '(const TArray, int)'
D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Private\MobuLiveLinkLayout.cpp(143): error C2530: 'SampleOption': references must be initialized
D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Private\MobuLiveLinkLayout.cpp(144): error C2228: left of '.Key' must have class/struct/union
  D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Private\MobuLiveLinkLayout.cpp(144): note: type is 'unknown-type'
D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Private\MobuLiveLinkLayout.cpp(144): error C2512: 'TStringConversion<FTCHARToUTF8_Convert,128>': no appropriate default constructor available
  D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Private\MobuLiveLinkLayout.cpp(144): note: No constructor could take the source type, or constructor overload resolution was ambiguous
D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Private\MobuLiveLinkLayout.cpp(144): error C2228: left of '.Get' must have class/struct/union
D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Private\MobuLiveLinkLayout.cpp(144): error C2228: left of '.c_str' must have class/struct/union
D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Private\MobuLiveLinkLayout.cpp(145): error C2228: left of '.Value' must have class/struct/union
  D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Private\MobuLiveLinkLayout.cpp(145): note: type is 'unknown-type'
D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Private\MobuLiveLinkLayout.cpp(145): error C2039: 'CurrentSampleRate': is not a member of 'FMobuLiveLink'
  D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Public\MobuLiveLinkDevice.h(22): note: see declaration of 'FMobuLiveLink'
D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Private\MobuLiveLinkLayout.cpp(312): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Private\MobuLiveLinkLayout.cpp(312): error C2143: syntax error: missing ';' before '&'
D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Private\MobuLiveLinkLayout.cpp(312): error C2065: 'NewSampleRate': undeclared identifier
D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Private\MobuLiveLinkLayout.cpp(312): error C2678: binary '[': no operator found which takes a left-hand operand of type 'const TArray' (or there is no acceptable conversion)
  d:\flavor\unrealengine\engine\source\runtime\core\public\Containers/Array.h(665): note: could be 'const InElementType &TArray<InElementType,InAllocator>::operator [](int32) const'
  d:\flavor\unrealengine\engine\source\runtime\core\public\Containers/Array.h(652): note: or       'InElementType &TArray<InElementType,InAllocator>::operator [](int32)'
  D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Private\MobuLiveLinkLayout.cpp(312): note: while trying to match the argument list '(const TArray, ORSDK2017::FBPropertyInt)'
D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Private\MobuLiveLinkLayout.cpp(312): error C2228: left of '.Value' must have class/struct/union
D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Private\MobuLiveLinkLayout.cpp(313): error C2065: 'NewSampleRate': undeclared identifier
D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Private\MobuLiveLinkLayout.cpp(313): error C2039: 'CurrentSampleRate': is not a member of 'FMobuLiveLink'
  D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Public\MobuLiveLinkDevice.h(22): note: see declaration of 'FMobuLiveLink'
D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Private\MobuLiveLinkLayout.cpp(315): error C2039: 'CurrentSampleRate': is not a member of 'FMobuLiveLink'
  D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Public\MobuLiveLinkDevice.h(22): note: see declaration of 'FMobuLiveLink'
D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Private\MobuLiveLinkLayout.cpp(315): error C2065: 'NewSampleRate': undeclared identifier
D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Private\MobuLiveLinkUtilities.cpp(185): error C2039: 'TimeModeToFrameRate': is not a member of 'MobuUtilities'
  D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Public\MobuLiveLinkUtilities.h(8): note: see declaration of 'MobuUtilities'
D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Private\MobuLiveLinkUtilities.cpp(185): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Private\MobuLiveLinkUtilities.cpp(185): error C2146: syntax error: missing ';' before identifier 'TimeModeToFrameRate'
D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Private\MobuLiveLinkUtilities.cpp(186): error C2143: syntax error: missing ';' before '{'
D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Private\MobuLiveLinkUtilities.cpp(186): error C2447: '{': missing function header (old-style formal list?)
D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Private\MobuLiveLinkUtilities.cpp(226): error C2065: 'FQualifiedFrameTime': undeclared identifier
D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Private\MobuLiveLinkUtilities.cpp(226): error C2065: 'SceneTimecode': undeclared identifier
D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Private\MobuLiveLinkUtilities.cpp(226): error C2761: 'void MobuUtilities::GetSceneTimecode(void)': member function redeclaration not allowed
D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\Private\MobuLiveLinkUtilities.cpp(227): error C2448: 'MobuUtilities::GetSceneTimecode': function-style initializer appears to be a function definitionModule.CoreUObject.4_of_6.cpp

D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\StreamObjects\Private\CameraStreamObject.cpp(53): error C2660: 'MobuUtilities::GetSceneTimecode': function does not take 1 arguments
D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\StreamObjects\Private\EditorActiveCameraStreamObject.cpp(105): error C2660: 'MobuUtilities::GetSceneTimecode': function does not take 1 arguments
D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\StreamObjects\Private\LightStreamObject.cpp(51): error C2660: 'MobuUtilities::GetSceneTimecode': function does not take 1 arguments
D:\flavor\UnrealEngine\Engine\Source\Programs\MobuLiveLink\Source\StreamObjects\Private\ModelStreamObject.cpp(169): error C2660: 'MobuUtilities::GetSceneTimecode': function does not take 1 arguments
  Module.CoreUObject.3_of_6.cpp
  Module.CoreUObject.2_of_6.cpp
  Module.CoreUObject.1_of_6.cpp
  Module.CoreUObject.gen.cpp
  Module.CoreUObject.6_of_6.cpp
  Module.Core.7_of_9.cpp
  Module.CoreUObject.5_of_6.cpp
  Module.Json.cpp
  [36/37] Resource PCLaunch.rc
  Module.Serialization.gen.cpp
UnrealBuildTool : error : UBT ERROR: Failed to produce item: D:\flavor\UnrealEngine\Engine\Binaries\Win64\MotionBuilder\MobuLiveLinkPlugin.dll
  Total build time: 80.63 seconds (Local executor: 0.00 seconds)
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.MakeFile.Targets(41,5): error MSB3075: The command "..\..\Build\BatchFiles\Build.bat MobuLiveLinkPlugin Win64 Development -WaitMutex -FromMsBuild" exited with code 5. Please verify that you have sufficient rights to run this command.
========== Build: 2 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by PatrickBoutotEpic** [comment]
You are trying to build the latest version of the plugin that can only be built against UE4.23+.
You may use a previous release in git.
