### ISSUE TITLE
Build for MOBU 2019

### ISSUE THREAD

**Issue by VRPlayhouse** [ue4plugins/MobuLiveLink#11]
Can someone post a build for Motion Builder 2019?  Currently there is an error message when using the 2018 plugin in Mobu 2019.

**Comment by liovch** [comment]
Any updates for the Mobu 2019 version? We've just upgraded to Mobu 2019, and the animation stream is now broken. I desperately need an updated MobuLiveLink for the upcoming demo, and going back to the older version of Mobu is not possible, unfortunately.

**Comment by SimonTherriaultEpic** [comment]
This should be resolved since 2.0 release. A 2019 build is now included.
