### ISSUE TITLE
MoBu 2020 support

### ISSUE THREAD

**Issue by SteKme** [ue4plugins/MobuLiveLink#17]
Hi,
please could it be possible to get the plugin updated for Windows MoBu 2020 as well? 
Thank You so much in advance!

**Comment by mlveggo** [comment]
Hi,

Check https://github.com/ue4plugins/MobuLiveLink/pull/18 out for MotionBuilder 2020 support.

**Comment by jiajiajibamaoss** [comment]
,I need the older version livelink  for mobu2015 ,need your help ,you are our technoledge leader ,thanks

**Comment by mattyjams** [comment]
Support for MotionBuilder 2020 and 2022 was added in 0762b9a7c8af90c5aa41f3a5e7f02eaa41ec4256, which was released with [version 2.5.0](https://github.com/ue4plugins/MobuLiveLink/releases/tag/v2.5.0).

Thanks!
