### ISSUE TITLE
MoBu 2015 support

### ISSUE THREAD

**Issue by jiajiajibamaoss** [ue4plugins/MobuLiveLink#19]
Hello,I need old version motionbuilder 2015 livelink plugins ,but I search all the web,get nothing , is there possible for me and for all of us who need the older version plugins ,thanks a lot.love livelink mobu2015

**Comment by mattyjams** [comment]
Hi @jiajiajibamaoss, unfortunately we will not be able to provide versions of the plugin for releases of MotionBuilder older than MotionBuilder 2016.

If you're comfortable building from source though, you may be able to use the code in this repo to build the version you need yourself. Building against MotionBuilder versions that old has not been tested though, so code changes may be required for it to work.
