### ISSUE TITLE
 Is there a compiled version?

### ISSUE THREAD

**Issue by LongBei-Bei** [ue4plugins/MobuLiveLink#22]
Hi!
Is there a compiled version? Compiling is too difficult for me.

**Comment by LongBei-Bei** [comment]
> Hi!
> Is there a compiled version? Compiling is too difficult for me.

I am referring to version 2.5.

**Comment by mattyjams** [comment]
A compiled release is now available for [version 2.5.0](https://github.com/ue4plugins/MobuLiveLink/releases/tag/v2.5.0). Apologies for the delay!

Thanks!
