### ISSUE TITLE
Mobu 2022 support

### ISSUE THREAD

**Issue by alexdjulin** [ue4plugins/MobuLiveLink#23]
Hi and thank your for this amazing plugin.

Is there a version for the latest mobu 2022? I would like to take advantage of the python3 integration while still being able to use the plugin.

Thank you.

**Comment by mattyjams** [comment]
Support for MotionBuilder 2020 and 2022 was added in 0762b9a7c8af90c5aa41f3a5e7f02eaa41ec4256, which was released with [version 2.5.0](https://github.com/ue4plugins/MobuLiveLink/releases/tag/v2.5.0).

Thanks!
