### ISSUE TITLE
Jitter

### ISSUE THREAD

**Issue by TheExiledLeader** [ue4plugins/MobuLiveLink#6]
When setting up a follow camera in UE4 to follow the data from MoBu Live Link there is random jitter in the skeleton joints on the UE4 end. This is not present when streaming the same exact data from the Maya Live Link.

**Comment by DrHibbitts** [comment]
Do you have an example of the issue or a reproduction I can use to test? 

Normally if there's Jitter it's because something isn't evaluating fast enough so I'd check your framerates in Motionbuilder and in Unreal as well as looking at increasing the sample rate in the device.

Thanks,
Dave

**Comment by TheExiledLeader** [comment]
Here's the documentation I've taken while doing testing.

Issue: Jitter on the mesh during movement when streaming from MoBu to UE4 through Live Link
	Appears to be from individual joints not whole mesh
		Character with separate mesh per joint, each mesh jitters individually
		Character with single mesh with skin weights, whole mesh jitters
	Visible with static camera
		More obvious with camera follow
		More prominent with faster movement (playback speed x5 in MoBu)
	Tried with plotted and non-plotted animation
	Tried at different frame rates in MoBu timeline
		Tested all UE4 Live Link refresh rates

UE4 System fps - ~90
MoBu System fps - Min: ~48, Max: ~90 during playback
MoBu Evaluation rate - Min: ~350, Max ~625 during playback


Set up the follow cam using a spring arm third person setup to follow useful joints
	Follow Pelvis
		Used snap to socket
		Used “set location”
	Follow Root: Constrained Root to Pelvis in MoBu
		Used snap to socket
		Used “set location”
Used Camera Streaming with Live Link
	Constrained follow camera in MoBu
		Smooth playback in MoBu
		Jittery playback in UE4

Issue persisted on both types of follows on both Joints in several setups
	No setup seemed to improve/worsen the jitter
Jitter gets better with lower playback speed and with a larger distance between camera and actor

Tested the same FBX file streaming from Maya
	No Issues
	Same camera follow BP

And this is the BP I'm using the drive the spring arm location:
![setcam_location](https://user-images.githubusercontent.com/41699945/43229295-2496bd26-9019-11e8-8575-a75c21c134b6.PNG)

**Comment by TheExiledLeader** [comment]
![ybot_maya_gif](https://user-images.githubusercontent.com/41699945/43233542-3ca7461c-902b-11e8-88e7-cec1fb9680ae.gif)

![ybot_mobu_gif](https://user-images.githubusercontent.com/41699945/43233547-417546a8-902b-11e8-899f-49c78a2b1958.gif)

**Comment by DrHibbitts** [comment]
Damn, that's a lot of jitter. Something seems very wrong there. 

Is this file sharable? If possible please email me at david.hibbitts@epicgames.com and I'll look into it. I've just tested a similar setup in 4.20 + Mobu 2017 and it's looking smooth.

It could be something to do with that rig that I've not encountered before, or something off in the setup of the device.

Thanks,
Dave
