### ISSUE TITLE
How ho get  focal length and  field of view sync?

### ISSUE THREAD

**Issue by sadauw** [ue4plugins/MobuLiveLink#9]
HI,

I am new to unreal engine, basically working as a Mocap Technician.
For motion builder live link I am following    https://www.youtube.com/watch?v=EPcGthmrWxw  
tutorial. Everything is working fine Except Focal Length And field of view is not syncing in unreal.

Thanks

**Comment by PatrickBoutotEpic** [comment]
We updated the workflow in 4.23. See https://docs.unrealengine.com/en-US/Engine/Animation/LiveLinkPlugin/index.html
Look for "Live Link Components". You may add the component to a camera actor. If the subject's role is a camera, the focal and field of view will be sync.
